name: project cicd flow
on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY:  cimaven.jfrog.io/docker-trial
  ACR_REGISTRY   :  cipoc.azurecr.io
  IMAGE_TAG: ${{ github.sha }}  # Use commit SHA as the tag for uniqueness
  IMAGE_NAME: springboot-images-new  #Replace with Authentic ones
  DOCKER_HUB_REGISTRY: docker.io

jobs:
  build:

    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version:  17
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

      # Docker login is replaced since Jfrog will be loaded with Actual image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #This is added as test part
    - name: Build & push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#Unit test
#Sonar test

    #- name: Setup Docker build
    #  uses: docker/setup-buildx-action@v1

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/docker-trial/springboot-images-new:latest,${{ env.ACR_REGISTRY }}/springboot-images-new:latest

      #Pull the Docker image from Docker Hub
    - name: Pull Docker image from Docker Hub
      run: docker pull ${{ env.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}






      
#---# Xray Jfrag

   # - name: Log in to Docker Hub
    #  uses: docker/login-action@v2
    #  with:
      #  username: ${{ secrets.DOCKER_USERNAME }}
      #  password: ${{ secrets.DOCKER_PASSWORD }}

   # - name: Build & push Docker image
   #   uses: docker/build-push-action@v5
    #  with:
    #    context: .
    #    file: ./Dockerfile
     #   push: true
    #    tags: deeptishalavadi/springboot-images-new:latest




        
