name: project cicd flow
on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY:  cimaven.jfrog.io/docker-trial
  ACR_REGISTRY   :  cipoc.azurecr.io
    

jobs:
  build:

    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version:  17
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Setup Docker build
      uses: docker/setup-buildx-action@v1
      
    - name: Login to JFrog
      uses: docker/login-action@v1
      with:
          # TODO: Change to secrets.name of your jFrog Service Account User Name
        username: ${{ secrets.JFROG_USERNAME }}
          # TODO: Change to secrets.name of your jFrog Service Account Api Key
        password: ${{ secrets.JFROG_API_KEY }}
        registry: ${{ env.DOCKER_REGISTRY }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        registry: ${{ env.ACR_REGISTRY }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/docker-trial/springboot-images-new:latest,${{ env.ACR_REGISTRY }}/springboot-images-new:latest


   # - name: Log in to Docker Hub
    #  uses: docker/login-action@v2
    #  with:
      #  username: ${{ secrets.DOCKER_USERNAME }}
      #  password: ${{ secrets.DOCKER_PASSWORD }}

   # - name: Build & push Docker image
   #   uses: docker/build-push-action@v5
    #  with:
    #    context: .
    #    file: ./Dockerfile
     #   push: true
    #    tags: deeptishalavadi/springboot-images-new:latest




        
